import os
import struct
from pathlib import Path
import flet as ft

# ==============================================================================
# CONFIGURAÇÕES E TRADUÇÕES
# ==============================================================================

PLUGIN_TRANSLATIONS = {
    "pt_BR": {
        "plugin_name": "PAC Devil May Cry 3 Special Edition (N. SWITCH)",
        "plugin_description": "Extrai e reconstrói arquivos PAC (Devil May Cry 3 Special Edition) Nintendo Switch",
        "select_pac_file": "Selecione um arquivo PAC",
        "select_list_file": "Selecione o arquivo .txt (lista) gerado pelo extrator",
        "invalid_file_magic": "Arquivo inválido: Magic incorreto (esperado 'PAC\\x00').",
        "file_not_found": "Arquivo não encontrado: {file}",
        "folder_not_found": "Pasta não encontrada: {folder}",
        "empty_list": "A lista está vazia.",
        "missing_files": "Arquivos ausentes:\n{files}",
        "replace_file_question": "O arquivo '{file}' já existe. Deseja substituir?",
        "extraction_completed": "Extração finalizada! Arquivos salvos em: {path}",
        "rebuild_completed": "PAC reconstruído com sucesso: {file}",
        "error_writing_pac": "Falha ao escrever o PAC: {error}",
        "error": "Erro",
        "completed": "Concluído",
        "cancelled": "Seleção cancelada.",
        "processing": "Processando: {name}...",
        "operation_completed": "Operação concluída."
    },
    "en_US": {
        "plugin_name": "PAC Devil May Cry 3 Special Edition (N. SWITCH)",
        "plugin_description": "Extracts and rebuilds PAC files (Devil May Cry 3 Special Edition) Nintendo Switch",
        "select_pac_file": "Select a PAC file",
        "select_list_file": "Select the .txt list file generated by the extractor",
        "invalid_file_magic": "Invalid file: Incorrect magic (expected 'PAC\\x00').",
        "file_not_found": "File not found: {file}",
        "folder_not_found": "Folder not found: {folder}",
        "empty_list": "The list is empty.",
        "missing_files": "Missing files:\n{files}",
        "replace_file_question": "The file '{file}' already exists. Do you want to replace it?",
        "extraction_completed": "Extraction completed! Files saved in: {path}",
        "rebuild_completed": "PAC successfully rebuilt: {file}",
        "error_writing_pac": "Failed to write PAC: {error}",
        "error": "Error",
        "completed": "Completed",
        "cancelled": "Selection cancelled.",
        "processing": "Processing: {name}...",
        "operation_completed": "Operation completed."
    },
    "es_ES": {
        "plugin_name": "PAC Devil May Cry 3 Special Edition (N. SWITCH)",
        "plugin_description": "Extrae y reconstruye archivos PAC (Devil May Cry 3 Special Edition) Nintendo Switch",
        "select_pac_file": "Seleccione un archivo PAC",
        "select_list_file": "Seleccione el archivo .txt (lista) generado por el extractor",
        "invalid_file_magic": "Archivo inválido: Magic incorrecto (se esperaba 'PAC\\x00').",
        "file_not_found": "Archivo no encontrado: {file}",
        "folder_not_found": "Carpeta no encontrada: {folder}",
        "empty_list": "La lista está vacía.",
        "missing_files": "Archivos ausentes:\n{files}",
        "replace_file_question": "El archivo '{file}' ya existe. ¿Desea reemplazarlo?",
        "extraction_completed": "¡Extracción finalizada! Archivos guardados en: {path}",
        "rebuild_completed": "PAC reconstruido con éxito: {file}",
        "error_writing_pac": "Fallo al escribir el PAC: {error}",
        "error": "Error",
        "completed": "Completado",
        "cancelled": "Selección cancelada.",
        "processing": "Procesando: {name}...",
        "operation_completed": "Operación completada."
    }
}

# Cores usadas no All For One
COLOR_LOG_GREEN = "#4ADE80"
COLOR_LOG_YELLOW = "#FACC15"
COLOR_LOG_RED = "#EF4444"

# Variáveis globais injetadas pelo sistema
logger = None
get_option = None
current_lang = "pt_BR"
host_page = None

def t(key, **kwargs):
    return PLUGIN_TRANSLATIONS.get(current_lang, PLUGIN_TRANSLATIONS["pt_BR"]).get(key, key).format(**kwargs)

# ==============================================================================
# FilePickers globais
# ==============================================================================

fp_extract = ft.FilePicker(
    on_result=lambda e: _extrair_pac(Path(e.files[0].path)) if e.files else logger(t("cancelled"), color=COLOR_LOG_YELLOW)
)

fp_rebuild = ft.FilePicker(
    on_result=lambda e: _reconstruir_pac(Path(e.files[0].path)) if e.files else logger(t("cancelled"), color=COLOR_LOG_YELLOW)
)

# ==============================================================================
# FUNÇÕES PRINCIPAIS (ADAPTADAS PARA USAR PATH E LOGGER)
# ==============================================================================

def _extrair_pac(file_path: Path):
    """Extrai arquivos do PAC selecionado."""
    logger(t("processing", name=file_path.name), color=COLOR_LOG_YELLOW)

    try:
        with open(file_path, "rb") as f:
            magic = f.read(4)
            if magic != b"PAC\x00":
                logger(t("invalid_file_magic"), color=COLOR_LOG_RED)
                return

            file_count = struct.unpack("<I", f.read(4))[0]

            pointers = []
            for _ in range(file_count):
                ptr = struct.unpack("<I", f.read(4))[0]
                pointers.append(ptr)

            out_dir = file_path.parent / file_path.stem
            out_dir.mkdir(parents=True, exist_ok=True)
            logger(t("extracting_to", path=str(out_dir)), color=COLOR_LOG_YELLOW)

            f.seek(0, os.SEEK_END)
            total_size = f.tell()

            extracted_files_list = []

            for i in range(file_count):
                start = pointers[i]
                end = pointers[i + 1] if i < file_count - 1 else total_size
                size = end - start
                f.seek(start)
                data = f.read(size)

                # Tenta adivinhar extensão a partir dos primeiros bytes
                ext = ".bin"
                if len(data) >= 3 and all(32 <= b < 127 for b in data[:3]):
                    try:
                        ext = "." + data[:3].decode("ascii").strip()
                    except:
                        pass

                file_name = f"{i+1:04}{ext}"
                extracted_files_list.append(file_name)

                out_path = out_dir / file_name
                with open(out_path, "wb") as out_file:
                    out_file.write(data)
                logger(t("file_extracted", filename=file_name), color=COLOR_LOG_GREEN)

            list_path = file_path.parent / (file_path.stem + ".txt")
            with open(list_path, "w", encoding="utf-8") as list_file:
                for name in extracted_files_list:
                    list_file.write(name + "\n")

            logger(t("extraction_completed", path=str(out_dir)), color=COLOR_LOG_GREEN)

    except FileNotFoundError:
        logger(t("file_not_found", file=str(file_path)), color=COLOR_LOG_RED)
    except Exception as e:
        logger(t("error") + ": " + str(e), color=COLOR_LOG_RED)


def _reconstruir_pac(list_path: Path):
    """Reconstrói o PAC a partir do arquivo de lista e pasta extraída."""
    logger(t("processing", name=list_path.name), color=COLOR_LOG_YELLOW)

    base = list_path.stem  # sem extensão .txt
    folder = list_path.parent / base
    if not folder.is_dir():
        logger(t("folder_not_found", folder=str(folder)), color=COLOR_LOG_RED)
        return

    try:
        with open(list_path, "r", encoding="utf-8") as f:
            lines = [ln.strip() for ln in f.readlines() if ln.strip()]
    except Exception as e:
        logger(t("error") + ": " + str(e), color=COLOR_LOG_RED)
        return

    if not lines:
        logger(t("empty_list"), color=COLOR_LOG_RED)
        return

    missing = [name for name in lines if not (folder / name).is_file()]
    if missing:
        logger(t("missing_files", files="\n".join(missing)), color=COLOR_LOG_RED)
        return

    file_count = len(lines)

    file_datas = []
    for name in lines:
        path = folder / name
        with open(path, "rb") as rf:
            file_datas.append(rf.read())

    header_size = 4
    count_size = 4
    pointers_size = 4 * file_count
    base_data_offset = header_size + count_size + pointers_size

    pointers = []
    current = base_data_offset
    for data in file_datas:
        pointers.append(current)
        current += len(data)

    out_pac = list_path.parent / (base + "_mod.pac")
    if out_pac.exists():
        logger(t("replace_file_question", file=str(out_pac)), color=COLOR_LOG_YELLOW)

    try:
        with open(out_pac, "wb") as out:
            out.write(b"PAC\x00")
            out.write(struct.pack("<I", file_count))
            for p in pointers:
                out.write(struct.pack("<I", p))
            for data in file_datas:
                out.write(data)
    except Exception as e:
        logger(t("error_writing_pac", error=str(e)), color=COLOR_LOG_RED)
        return

    logger(t("rebuild_completed", file=str(out_pac)), color=COLOR_LOG_GREEN)


# ==============================================================================
# AÇÕES DOS COMANDOS (CHAMAM OS FILEPICKERS)
# ==============================================================================

def action_extract():
    fp_extract.pick_files(
        allowed_extensions=["pac"],
        dialog_title=t("select_pac_file")
    )

def action_rebuild():
    fp_rebuild.pick_files(
        allowed_extensions=["txt"],
        dialog_title=t("select_list_file")
    )


# ==============================================================================
# ENTRY POINT (REGISTRO)
# ==============================================================================
def register_plugin(log_func, option_getter, host_language="pt_BR", page=None):
    global logger, get_option, current_lang, host_page
    logger = log_func
    get_option = option_getter
    current_lang = host_language
    host_page = page

    if host_page:
        host_page.overlay.extend([fp_extract, fp_rebuild])
        host_page.update()

    return {
        "name": t("plugin_name"),
        "description": t("plugin_description"),
        "commands": [
            {"label": t("select_pac_file"), "action": action_extract},
            {"label": t("select_list_file"), "action": action_rebuild},
        ]
    }