import os
import struct
from pathlib import Path
import tkinter as tk
from tkinter import filedialog

# ==============================================================================
# CONFIGURAÇÕES E TRADUÇÕES
# ==============================================================================

PLUGIN_TRANSLATIONS = {
    "pt_BR": {
        "plugin_name": "PAC Devil May Cry 3 Special Edition (N. SWITCH)",
        "plugin_description": "Extrai e reconstrói arquivos PAC (Devil May Cry 3 Special Edition) Nintendo Switch",
        "select_pac_file": "Selecione um arquivo PAC",
        "select_list_file": "Selecione o arquivo .txt (lista) gerado pelo extrator",
        "invalid_file_magic": "Arquivo inválido: Magic incorreto (esperado 'PAC\\x00').",
        "file_not_found": "Arquivo não encontrado: {file}",
        "folder_not_found": "Pasta não encontrada: {folder}",
        "empty_list": "A lista está vazia.",
        "missing_files": "Arquivos ausentes:\n{files}",
        "replace_file_question": "O arquivo '{file}' já existe. Deseja substituir?",
        "extraction_completed": "Extração finalizada! Arquivos salvos em: {path}",
        "rebuild_completed": "PAC reconstruído com sucesso: {file}",
        "error_writing_pac": "Falha ao escrever o PAC: {error}",
        "error": "Erro",
        "completed": "Concluído",
        "cancelled": "Seleção cancelada.",
        "processing": "Processando: {name}...",
        "operation_completed": "Operação concluída."
    },
    "en_US": {
        "plugin_name": "PAC Devil May Cry 3 Special Edition (N. SWITCH)",
        "plugin_description": "Extracts and rebuilds PAC files (Devil May Cry 3 Special Edition) Nintendo Switch",
        "select_pac_file": "Select a PAC file",
        "select_list_file": "Select the .txt list file generated by the extractor",
        "invalid_file_magic": "Invalid file: Incorrect magic (expected 'PAC\\x00').",
        "file_not_found": "File not found: {file}",
        "folder_not_found": "Folder not found: {folder}",
        "empty_list": "The list is empty.",
        "missing_files": "Missing files:\n{files}",
        "replace_file_question": "The file '{file}' already exists. Do you want to replace it?",
        "extraction_completed": "Extraction completed! Files saved in: {path}",
        "rebuild_completed": "PAC successfully rebuilt: {file}",
        "error_writing_pac": "Failed to write PAC: {error}",
        "error": "Error",
        "completed": "Completed",
        "cancelled": "Selection cancelled.",
        "processing": "Processing: {name}...",
        "operation_completed": "Operation completed."
    },
    "es_ES": {
        "plugin_name": "PAC Devil May Cry 3 Special Edition (N. SWITCH)",
        "plugin_description": "Extrae y reconstruye archivos PAC (Devil May Cry 3 Special Edition) Nintendo Switch",
        "select_pac_file": "Seleccione un archivo PAC",
        "select_list_file": "Seleccione el archivo .txt (lista) generado por el extractor",
        "invalid_file_magic": "Archivo inválido: Magic incorrecto (se esperaba 'PAC\\x00').",
        "file_not_found": "Archivo no encontrado: {file}",
        "folder_not_found": "Carpeta no encontrada: {folder}",
        "empty_list": "La lista está vacía.",
        "missing_files": "Archivos ausentes:\n{files}",
        "replace_file_question": "El archivo '{file}' ya existe. ¿Desea reemplazarlo?",
        "extraction_completed": "¡Extracción finalizada! Archivos guardados en: {path}",
        "rebuild_completed": "PAC reconstruido con éxito: {file}",
        "error_writing_pac": "Fallo al escribir el PAC: {error}",
        "error": "Error",
        "completed": "Completado",
        "cancelled": "Selección cancelada.",
        "processing": "Procesando: {name}...",
        "operation_completed": "Operación completada."
    }
}

# Cores usadas no All For One
COLOR_LOG_GREEN = "#4ADE80"
COLOR_LOG_YELLOW = "#FACC15"
COLOR_LOG_RED = "#EF4444"

# Variáveis globais injetadas pelo sistema
logger = None
get_option = None
current_lang = "pt_BR"

def t(key, **kwargs):
    return PLUGIN_TRANSLATIONS.get(current_lang, PLUGIN_TRANSLATIONS["pt_BR"]).get(key, key).format(**kwargs)

# ==============================================================================
# FUNÇÃO PARA CORRIGIR A JANELA (TOPMOST)
# ==============================================================================
def pick_file_topmost(title, file_types):
    root = tk.Tk()
    root.withdraw()
    root.wm_attributes('-topmost', 1)
    file_path = filedialog.askopenfilename(parent=root, title=title, filetypes=file_types)
    root.destroy()
    return file_path

# ==============================================================================
# FUNÇÕES PRINCIPAIS (ADAPTADAS PARA USAR LOGGER)
# ==============================================================================

def extrair_pac(file_path):
    try:
        with open(file_path, "rb") as f:
            magic = f.read(4)
            if magic != b"PAC\x00":
                logger(t("invalid_file_magic"), color=COLOR_LOG_RED)
                return

            file_count = struct.unpack("<I", f.read(4))[0]

            pointers = []
            for _ in range(file_count):
                ptr = struct.unpack("<I", f.read(4))[0]
                pointers.append(ptr)

            out_dir = os.path.join(os.path.dirname(file_path), os.path.splitext(os.path.basename(file_path))[0])
            os.makedirs(out_dir, exist_ok=True)
            logger(t("extracting_to", path=out_dir), color=COLOR_LOG_YELLOW)

            f.seek(0, os.SEEK_END)
            total_size = f.tell()

            extracted_files_list = []

            for i in range(file_count):
                start = pointers[i]
                end = pointers[i + 1] if i < file_count - 1 else total_size
                size = end - start
                f.seek(start)
                data = f.read(size)

                ext = ".bin"
                if len(data) >= 3 and all(32 <= b < 127 for b in data[:3]):
                    try:
                        ext = "." + data[:3].decode("ascii").strip()
                    except:
                        pass

                file_name = f"{i+1:04}{ext}"
                extracted_files_list.append(file_name)

                out_path = os.path.join(out_dir, file_name)
                with open(out_path, "wb") as out_file:
                    out_file.write(data)
                logger(t("file_extracted", filename=file_name), color=COLOR_LOG_GREEN)

            list_path = out_dir + ".txt"
            with open(list_path, "w", encoding="utf-8") as list_file:
                for name in extracted_files_list:
                    list_file.write(name + "\n")

            logger(t("extraction_completed", path=out_dir), color=COLOR_LOG_GREEN)

    except FileNotFoundError:
        logger(t("file_not_found", file=file_path), color=COLOR_LOG_RED)
    except Exception as e:
        logger(t("error") + ": " + str(e), color=COLOR_LOG_RED)


def reconstruir_pac(list_path):
    base = os.path.splitext(list_path)[0]
    folder = base
    if not os.path.isdir(folder):
        logger(t("folder_not_found", folder=folder), color=COLOR_LOG_RED)
        return

    try:
        with open(list_path, "r", encoding="utf-8") as f:
            lines = [ln.strip() for ln in f.readlines() if ln.strip()]
    except Exception as e:
        logger(t("error") + ": " + str(e), color=COLOR_LOG_RED)
        return

    if not lines:
        logger(t("empty_list"), color=COLOR_LOG_RED)
        return

    missing = [name for name in lines if not os.path.isfile(os.path.join(folder, name))]
    if missing:
        logger(t("missing_files", files="\n".join(missing)), color=COLOR_LOG_RED)
        return

    file_count = len(lines)

    file_datas = []
    for name in lines:
        path = os.path.join(folder, name)
        with open(path, "rb") as rf:
            file_datas.append(rf.read())

    header_size = 4
    count_size = 4
    pointers_size = 4 * file_count
    base_data_offset = header_size + count_size + pointers_size

    pointers = []
    current = base_data_offset
    for data in file_datas:
        pointers.append(current)
        current += len(data)

    out_pac = base + "_mod.pac"
    if os.path.exists(out_pac):
        # Sem interação com o usuário – simplesmente sobrescreve (ou pode-se adicionar uma opção, mas manteremos simples)
        logger(t("replace_file_question", file=out_pac), color=COLOR_LOG_YELLOW)

    try:
        with open(out_pac, "wb") as out:
            out.write(b"PAC\x00")
            out.write(struct.pack("<I", file_count))
            for p in pointers:
                out.write(struct.pack("<I", p))
            for data in file_datas:
                out.write(data)
    except Exception as e:
        logger(t("error_writing_pac", error=str(e)), color=COLOR_LOG_RED)
        return

    logger(t("rebuild_completed", file=out_pac), color=COLOR_LOG_GREEN)


# ==============================================================================
# AÇÕES DOS COMANDOS (SEM THREADING)
# ==============================================================================

def action_extract():
    path = pick_file_topmost(t("select_pac_file"), [("PAC files", "*.pac"), (t("all_files"), "*.*")])
    if not path:
        logger(t("cancelled"), color=COLOR_LOG_YELLOW)
        return
    logger(t("processing", name=os.path.basename(path)), color=COLOR_LOG_YELLOW)
    extrair_pac(path)


def action_rebuild():
    path = pick_file_topmost(t("select_list_file"), [("Text files", "*.txt"), (t("all_files"), "*.*")])
    if not path:
        logger(t("cancelled"), color=COLOR_LOG_YELLOW)
        return
    logger(t("processing", name=os.path.basename(path)), color=COLOR_LOG_YELLOW)
    reconstruir_pac(path)


# ==============================================================================
# ENTRY POINT (REGISTRO)
# ==============================================================================
def register_plugin(log_func, option_getter, host_language="pt_BR"):
    global logger, get_option, current_lang
    logger = log_func
    get_option = option_getter
    current_lang = host_language

    return {
        "name": t("plugin_name"),
        "description": t("plugin_description"),
        "commands": [
            {"label": t("select_pac_file"), "action": action_extract},
            {"label": t("select_list_file"), "action": action_rebuild},
        ]
    }